BPLLCWEB/Controllers/ContactUsController.cs
using BPLLCWEB.Domain.Entities;
using BPLLCWEB.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BPLLCWEB.Classes;
using BPLLCWEB.Helpers;

namespace BPLLCWEB.Controllers
{
    public class ContactUsController : Controller
    {
        private IRepository repository;
        private IProcessor processor;

        public ContactUsController(IRepository repo, IProcessor proc)
        {
            repository = repo;
            processor = proc;
        }

        public ActionResult Contacts()
        {
            return View();
        }

        public ActionResult ContactUs(string contactcode)
        {
            if (String.IsNullOrEmpty(contactcode))
            {
                return RedirectToAction("/Contacts");
            }
            else
            {
                ViewBag.ContactCode = HttpUtility.HtmlEncode(contactcode);
                ViewBag.Subject = Reusables.ContactSubject(ViewBag.ContactCode);

                return View(new ContactInfo());
            }
        }

        [HttpPost]
        public ActionResult ContactUs(ContactInfo contactinfo)
        {
            ViewBag.Subject = Request["subject"]; // passing the value again to ViewBag.Message

            if (ModelState.IsValid)
            {
                if (!ArithmeticCaptcha.isValid(Request["ArithmeticValue"], Request["ArithmeticValueEnc"]))
                {
                    //ModelState.AddModelError("ArithmeticValue", "Wrong number. Please try again.");
                    ViewBag.WrongNumber = "Wrong number. Please try again.";
                }
                else
                {
                    ViewBag.Successful = "Your Form has been submitted successfully!";
                    ViewBag.WrongNumber = "";

                    string mailtoAddress = Reusables.ContactRecipient(contactinfo.ContactCode);

                    //*** for testing ***
                    //mailtoAddress = "sung.park@businesspartnersllc.com";

                    contactinfo.MailToAddress = mailtoAddress;
                    string subject = ViewBag.Subject;

                    if (!String.IsNullOrEmpty(mailtoAddress))
                    {
                        // send email
                        processor.ProcessContactInfo(contactinfo);
                    }
                }
            }
            return View();
        }
	}
}

BPLLCWEB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BPLLCWEB.Domain.Entities;
using BPLLCWEB.Domain.Abstract;
using BPLLCWEB.Domain.Concrete;
using BPLLCWEB.Classes;
using BPLLCWEB.Helpers;
using System.Configuration;
using System.Text;
using System.Data.Entity;

namespace BPLLCWEB.Controllers
{
    public class HomeController : Controller
    {
        private IRepository repository;
        private IProcessor processor;

        public HomeController(IRepository repo, IProcessor proc)
        {
            repository = repo;
            processor = proc;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult WhoWeAre()
        {
            return View();
        }

        public ActionResult PartnerWithUs()
        {
            return View();
        }
        public ActionResult Careers()
        {
            return View();
        }

        public ActionResult ServicesOrigination()
        {
            return View();
        }

        public ActionResult ServicesProcessing()
        {
            return View();
        }

        public ActionResult ServicesAsset()
        {
            return View();
        }

        public ActionResult ServicesLoanReferral()
        {
            return View();
        }

        public ActionResult PortfolioManagement()
        {
            return View();
        }

        public ActionResult LoansGeneral()
        {
            return View();
        }

        public ActionResult LoansSBA()
        {
            return View();
        }

        public ActionResult LoansCRE()
        {
            return View();
        }

        public ActionResult LoansSBS()
        {
            return View();
        }

        public ActionResult ParticipationGeneral()
        {
            return View();
        }

        public ActionResult ParticipationSignUp()
        {
            return View();
        }

        public ActionResult Faq()
        {
            return View();
        }

        public ActionResult IndustryNews()
        {
            return View();
        }    

        public ActionResult REONotesSale()
        {
            return View();
        }

        public ActionResult RecentFundings()
        {
            return View();
        }

        public ActionResult Broker()
        {
            return View();
        }

        public ActionResult ValidateLogin()
        {
            string username = Request["username"];
            string password = Request["password"];
            string ipaddress = Request.Params["REMOTE_ADDR"];

            try
            {
                if (!String.IsNullOrEmpty(username))
                {
                    // determine lock first
                    if (Linqs.DetemineLock(ipaddress))
                    {
                        // display account locked message
                        processor.ProcessHackAttemptEmail(ipaddress, username, password);

                        TempData["Message"] = "Your organization has been locked out from this site. Please try again later.";
                        return RedirectToAction("Login");
                    }
                    else
                    {
                        // validate login
                        if (Linqs.ValidateLogin(username, password))
                        {                           
                            return RedirectToAction("Index", "CU");
                        }
                        else
                        {
                            // save a record into loginattempts
                            Linqs.InsertLoginAttempt(ipaddress);

                            TempData["Message"] = "Your account is not valid. Please try again.";
                            return RedirectToAction("Login");
                        }
                    }
                }
                else
                {
                    TempData["Message"] = "Login account not found.";
                    return RedirectToAction("Login");
                }
            }
            catch (Exception ex)
            {
                processor.ProcessSendErrorEmail(ex.Message + "\n\n" + ex.ToString(), "BP ValidateLogin");
                TempData["Message"] = "Some error has occurred. Please try again later.";
                return RedirectToAction("Login");
            }
        }

        public ActionResult Login(int id)
        {
            if (id == 1)
            {
                TempData["Message"] = "Your session has expired. Please log in again.";
            }

            return View();
        }

        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            string ipaddress = Request.Params["REMOTE_ADDR"];

            // for testing
            ipaddress = "10.0.0.69";

            try
            {
                if (!String.IsNullOrEmpty(username) && !String.IsNullOrEmpty(password))
                {
                    // determine lock first
                    if (Linqs.DetemineLock(ipaddress))
                    {
                        // display account locked message
                        processor.ProcessHackAttemptEmail(ipaddress, username, password);

                        TempData["Message"] = "Your organization has been locked out from this site. Please try again later.";
                        return View();
                    }
                    else
                    {
                        // validate login
                        if (Linqs.ValidateLogin(username, password))
                        {
                            return RedirectToAction("Index", "CU");
                        }
                        else
                        {
                            // save a record into loginattempts
                            Linqs.InsertLoginAttempt(ipaddress);

                            TempData["Message"] = "Your account is not valid. Please try again.";
                            return View();
                        }
                    }
                }
                else
                {
                    TempData["Message"] = "Username and/or Password is missing.";
                    return View();
                }
            }
            catch (Exception ex)
            {
                processor.ProcessSendErrorEmail(ex.Message + "\n\n" + ex.ToString(), "BP HttpPost Login");
                TempData["Message"] = "Some error has occurred. Please try again later.";
                return View();
            }
        }

        public ActionResult ForgottenPassword()
        {
            return View();
        }

        public ActionResult SecretQA()
        {
            Logins login = new Logins();
            login.UID = (int)TempData["UID"];
            login.UserName = (string)TempData["UserName"];
            login.SecretQuestion = (string)TempData["Question"];
            login.Errors = (int)TempData["Errors"];

            return View(login);
        }

        [HttpPost]
        public ActionResult ForgottenPassword(ValidateUser user)
        {
            bool valid = false;
            int errors = 0, uid = 0;
            string username = null, question = null;

            try
            {
                if (String.IsNullOrEmpty(user.UserName) && String.IsNullOrEmpty(user.EmailAdd))
                {
                    ViewBag.Message = "Either Username Or Email Address needs to be entered.";
                }
                else
                {
                    // check if username OR email address is valid
                    if (!String.IsNullOrEmpty(user.UserName))
                    {
                        if (Linqs.CheckUserName(ref uid, user.UserName, ref question, ref errors))
                        {
                            TempData["UID"] = uid;
                            TempData["UserName"] = user.UserName;
                            TempData["Question"] = question;
                            TempData["Errors"] = errors;
                            valid = true;
                        }
                    }
                    else
                    {
                        if (Linqs.CheckEmailAddress(user.EmailAdd, ref uid, ref username, ref question, ref errors))
                        {
                            TempData["UID"] = uid;
                            TempData["UserName"] = username;
                            TempData["Question"] = question;
                            TempData["Errors"] = errors;
                            valid = true;
                        }
                    }

                    if (!valid)
                    {
                        ViewBag.Message = "Incorrect entry. Please try again.";
                    }
                    else
                    {
                        if (errors > 2)
                        {
                            ViewBag.Message = "Your account has been locked. You can unlock your account by contacting the web administrator via email at sung.park@businesspartnersllc.com or john.sowter@businesspartnersllc.com.";
                        }
                        else
                        {
                            return RedirectToAction("SecretQA");
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                processor.ProcessSendErrorEmail(ex.Message + "\n\n" + ex.ToString(), "BP ForgottenPassword");
                ViewBag.Message = "Some error has occurred. Please try again later.";                
            }

            return View();
        }

        [HttpPost]

BPLLCWEB/Views/Home/Broker.cshtml
@model BPLLCWEB.Domain.Entities.BrokerInfo

@{
    ViewBag.Title = "Broker Resources";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string successful = ViewBag.Successful;
    string wrongnumber = ViewBag.WrongNumber;
}

@using BPLLCWEB.Helpers

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<fieldset id="navpagefieldset">

    <div class="navHeader">
        Broker Resources
    </div>

    <div id="navBody">

        <table>

            @*not template begin*@

            <tr>
                <td style="width: 620px">
                    Business Partners
                    offers competitively priced commercial real estate loans. Our program
                    offers a range of pricing options to better serve your clients.
                    We offer the flexibility in terms you expect in a small community
                    bank with the lending power of a large national financial institution.
                    Our network of participants allows us to fund loans from $500,000
                    to $50,000,000 in a process that is seamless to your client.

                    <br /><br />

                    Business Partners
                    funded over $500,000,000 in 2005. Make the choice that has proven
                    successful for so many. Choose Business Partners on your next transaction.

                    <br /><br />

                    <strong>Become An Approved Broker!</strong><br>
                    For more information regarding our program, or to become an approved broker, please complete and submit the form below and a BPLLC Loan Officer will contact you.

                    <br /><br />


                    @using (Html.BeginForm())
                    {
                        @Html.ValidationSummary()

                        <fieldset id="contactfieldset">
                            <legend>&nbsp;&nbsp;<strong>Broker Request for Information</strong>&nbsp;&nbsp;</legend>
                               
                            <table>
                                <tr>
                                    <td>
                                        <table>
                                            <tr><td colspan="2" height="10"></td></tr>
                                            <tr>
                                                <td colspan="2"><font color="red">@successful</font></td>
                                            </tr>
                                            <tr style="vertical-align: top">
                                                <td width="180px">
                                                    <div class="editor-label">
                                                        <strong><font color="red">*</font>&nbsp;Brokerage Firm:</strong>
                                                    </div>
                                                </td>
                                                <td>
                                                    @Html.TextBoxFor(c => c.BrokerageName, new { style = "width: 280px", id = "firsttextbox" })
                                                </td>
                                            </tr>

                                            <tr>
                                                <td>
                                                    <div class="editor-label">
                                                        <strong><font color="red">*</font>&nbsp;Broker Contact:</strong>
                                                    </div>
                                                </td>
                                                <td>
                                                    @Html.TextBoxFor(c => c.BrokertName, new { style = "width: 280px" })
                                                </td>
                                            </tr>

                                            <tr>
                                                <td>
                                                    <div class="editor-label">
                                                        <strong><font color="red">*</font>&nbsp;Phone Number:</strong>
                                                    </div>
                                                </td>
                                                <td>
                                                    @Html.TextBoxFor(c => c.PhoneNumber, new { style = "width: 280px" })
                                                </td>
                                            </tr>

                                            <tr>
                                                <td>
                                                    <div class="editor-label">
                                                        <strong><font color="red">*</font>&nbsp;Email Address:</strong>
                                                    </div>
                                                </td>
                                                <td>
                                                    @Html.TextBoxFor(c => c.EmailAddress, new { style = "width: 280px" })
                                                </td>
                                            </tr>

                                            <tr>
                                                <td colspan="2">
                                                    <div class="editor-label">
                                                        <strong>Please enter the number: </strong>@Html.CaptchaCalculationAnswer(15, "ArithmeticValue")
                                                        @Html.TextBox("ArithmeticValue")
                                                    </div>
                                                </td>
                                            </tr>

                                            <tr>
                                                <td colspan="2">
                                                    <font color="red">@wrongnumber</font>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>

                                <tr>
                                    <td>
                                        <div class="editor-label">
                                            <input type="submit" value="Submit" class="boxsubmit">
                                        </div>

                                    </td>
                                </tr>

                            </table>

                        </fieldset>
                    }



                    <br />
                    
                    To apply now, simply download, complete and mail-in the CRE Broker Package below.
                    
                    <br /><br />

                    <a href="/Downloads/BrokerApplication.pdf">Click here to download CRE Broker Package</a>&nbsp;<font size="2">(Acrobat PDF: 156KB)</font>

</td>
 
            </tr>


            @*not template end*@

        </table>

    </div>

</fieldset>


<script type="text/javascript">
    $(document).ready(function () {

        $(function () {
            $('#firsttextbox').focus();
        });
    });
</script>

BPLLCWEB/Views/Home/Careers.cshtml
@{
    ViewBag.Title = "Careers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<fieldset id="navpagefieldset">

    <div id="navBody">

        <table>

            @*not template begin*@

            <tr>
                <td>
                    <iframe align="middle" style="vertical-align:top; width: 910px" frameborder="0" src="https://secure.sterlingdirect.com/jobboard/default.aspx?JOBBOARDID=58&amp;" height="700" scrolling="auto"></iframe>

                </td>
            </tr>


            @*not template end*@

        </table>

    </div>

</fieldset>

BPLLCWEB/Views/Home/ForgottenPassword.cshtml
@model BPLLCWEB.Domain.Entities.ValidateUser

@{
    ViewBag.Title = "Forgotten Password";
    string message = ViewBag.Message;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<fieldset id="navpagefieldset">

    <div class="navHeader">
        Retrieve Password
    </div>

    <div id="navBody">

        <table>

            @*not template begin*@

            <tr>
                <td style="width: 620px">

                    @using (Html.BeginForm())
                    {
                        @Html.ValidationSummary()

                        <fieldset id="contactfieldset">
                            <legend>&nbsp;&nbsp;<strong>Step 1</strong>&nbsp;&nbsp;</legend>
                            <br />
                            Please enter your username OR email address to continue.
                            <br />

                            <table>
                                <tr>
                                    <td>
                                        <table>
                                            <tr><td colspan="2" height="10"></td></tr>
                                            <tr>
                                                <td colspan="2"><font color="red">@message</font></td>
                                            </tr>
                                            <tr style="vertical-align: top">
                                                <td width="120px">
                                                    <div class="editor-label">
                                                        <strong>Username:</strong>
                                                    </div>
                                                </td>
                                                <td>
                                                    @Html.TextBox("UserName", null, new { style = "width: 280px", id = "Username" })
                                                </td>
                                            </tr>
                                            <tr><td colspan="2"><br />OR</td></tr>
                                            <tr>
                                                <td>
                                                    <div class="editor-label">
                                                        <strong>Email Address:</strong>
                                                    </div>
                                                </td>
                                                <td>
                                                    @Html.TextBox("EmailAdd", null, new { style = "width: 280px" })
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr><td height="10"></td></tr>
                                <tr>
                                    <td>
                                        <div class="editor-label">
                                            <input type="submit" value="Continue" class="boxsubmit">
                                        </div>

                                    </td>
                                </tr>

                            </table>

                        </fieldset>

                    }

                </td>

            </tr>


            @*not template end*@

        </table>

    </div>

</fieldset>



<script type="text/javascript">
    $(document).ready(function () {

        $(function() {
            $("#Username").focus();
        });
    });
</script>

BPLLCWEB/Views/Home/PortfolioManagement.cshtml
@{
    ViewBag.Title = "Portfolio Management";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<fieldset id="navpagefieldset">

    <div class="navHeader">
        Portfolio Management
    </div>

    <div id="navBody">

        <table>

            @*not template begin*@

            <tr>
                <td style="width: 620px">
                    Business Partners can provide your organization with both the lending capacity<br />
                    to grow loans and the asset management services to maintain portfolio profitability.<br />
                    There’s no need to invest in costly infrastructure to manage your loan risk - we handle
                    everything, including:

                    <br /><br />

                    <ul>
                        <li id="navBodyLi">Periodic analysis of borrower financial performance and credit rating</li>
                        <li id="navBodyLi">Loan asset valuation</li>
                        <li id="navBodyLi">Loan risk rating to effectively categorize your risk levels</li>
                        <li id="navBodyLi">Loan covenant monitoring</li>
                    </ul>

                    <br />

                    @Html.ActionLink("Click here", "ContactUs", "ContactUs", new { contactcode = "osbal" }, null)
                    to be contacted by one of our lending experts to discuss your organization’s<br />
                    portfolio management needs.

                </td>
                <td style="vertical-align: top;">
                    <img src="/images/Services/Portfolio management.jpg" width="280" title="Portfolio Management" />
                </td>
            </tr>


            @*not template end*@

        </table>

    </div>

</fieldset>

BPLLCWEB/Views/Home/ServicesAsset.cshtml
@{
    ViewBag.Title = "Services Asset";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<fieldset id="navpagefieldset">

    <div class="navHeader">
        Loan Servicing, Reporting and Collection
    </div>

    <div id="navBody">

        <table>

            @*not template begin*@

            <tr>
                <td style="width: 620px">
                    Building a profitable lending program means taking on additional risk. Business Partners<br />
                    will support your organization with comprehensive asset and risk management tools. <br />
                    Our transparent approach to underwriting and risk management is based on providing<br />
                    extensive support documentation and timely, in-depth loan reviews and inspection<br />
                    reports —including on-going monitoring of asset quality and the ability of borrowers<br />
                    to pay— that your examiners, auditors, management and board members will appreciate.

                    <br /><br />

                    Business Partners also offers comprehensive collection services to help keep loan<br />
                    repayment current. From payment reminders, late notices and direct communication,<br />
                    we can facilitate timely repayment from your borrowers.

                    <br /><br />

                    
                    @Html.ActionLink("Click here", "ContactUs", "ContactUs", new { contactcode = "osbal" }, null)
                    to be contacted by one of our lending experts to discuss your organization’s<br />
                    loan servicing needs.

                </td>
                <td style="vertical-align: top;">
                    <img src="/images/Services/Loan servicing.jpg" width="280" title="Loan Servicing, Reporting and Collection" />
                </td>
            </tr>


            @*not template end*@

        </table>

    </div>

</fieldset>

BPLLCWEB/Views/Home/WhoWeAre.cshtml
@{
    ViewBag.Title = "Who We Are";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<fieldset id="navpagefieldset">
    
    <div class="navHeader">
        Who We Are
    </div>

    <div id="navBody">

        <table>

                @*not template begin*@

                <tr>
                    <td style="width: 620px">
                        Business Partners is a nationwide provider of superior small business and commercial<br />
                        real estate lending services, designed to broaden and diversify our clients’ asset base<br />
                        and enhance revenues. With years of experience, and a focus on extraordinary service<br />
                        and support, we’re experts at building customer profitability and satisfaction.
                        <br /><br />
                        Business Partners was created in 1995 as a <a href="/Home/PartnerWithUs">strategic partner</a> for financial institutions<br />
                        needing expertise in commercial real estate and small business lending. Today,<br />
                        we support a nationwide base of lenders and brokers by providing the tools and<br />
                        infrastructure essential for loan portfolio growth.<br /><br />

                        Our services include:
                        <ul>
                            <li id="navBodyLi"><a href="/Home/ServicesOrigination">Loan origination</a></li>
                            <li id="navBodyLi"><a href="/Home/ServicesProcessing">Processing and Underwriting</a></li>
                            <li id="navBodyLi"><a href="/Home/PortfolioManagement">Portfolio management</a></li>
                            <li id="navBodyLi"><a href="/Home/ServicesAsset">Loan servicing, reporting and collection</a></li>
                            <li id="navBodyLi"><a href="/Home/ParticipationGeneral">Participation aggregation and management</a></li>
                        </ul>
                    </td>
                    <td style="vertical-align: top;">
                        <img src="/images/AboutUs/Who we are.jpg" width="280" title="Who We Are" />
                    </td>
                </tr>

                <tr>
                    <td>
                        <br />
                        No matter what services you need, we can help your organization to:
                        <ul>
                            <li id="navBodyLi">Enhance income</li>
                            <li id="navBodyLi">Expand your asset base</li>
                            <li id="navBodyLi">Diversify your loan portfolio</li>
                            <li id="navBodyLi">Enjoy better lending support and service</li>
                            <li id="navBodyLi">
                                Gain the competitive advantage brought by Business Partners’ expertise and
                                marketplace knowledge
                            </li>
                        </ul>
                        <br />
                        @Html.ActionLink("Click here", "ContactUs", "ContactUs", new { contactcode = "crel" }, null)
                        to be contacted by one of our lending experts to discuss your<br />
                        organization’s specific needs.

                    </td>
                </tr>

                @*not template end*@

            </table>
         
     </div>

</fieldset>